"""create appointments table

Revision ID: 1ac683497a70
Revises: a8d42958811e
Create Date: 2026-06-18 17:53:23.014333
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1ac683497a70'
down_revision = 'a8d42958811e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
