"""create doctors table

Revision ID: 277a4233f4cb
Revises: 2c53dd2c48f5
Create Date: 2026-06-18 12:59:50.727579
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '277a4233f4cb'
down_revision = '2c53dd2c48f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('credentials', sa.String(length=255), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('consultation_location', sa.String(length=255), nullable=True),
    sa.Column('availability_summary', sa.String(length=255), nullable=True),
    sa.Column('is_accepting_new_patients', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_full_name'), 'doctors', ['full_name'], unique=False)
    op.create_index(op.f('ix_doctors_specialty'), 'doctors', ['specialty'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctors_specialty'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_full_name'), table_name='doctors')
    op.drop_table('doctors')
    # ### end Alembic commands ###
