"""create payments table

Revision ID: 588d6bdea871
Revises: 1dbe774e3ad1
Create Date: 2026-06-18 18:13:12.182393
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '588d6bdea871'
down_revision = '1dbe774e3ad1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
