"""create reviews table

Revision ID: 75369e02cefc
Revises: 588d6bdea871
Create Date: 2026-06-18 18:35:35.123209
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '75369e02cefc'
down_revision = '588d6bdea871'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=True),
    sa.Column('service_id', sa.Uuid(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(doctor_id IS NOT NULL AND service_id IS NULL) OR (doctor_id IS NULL AND service_id IS NOT NULL)', name='ck_reviews_exactly_one_target'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_doctor_id'), 'reviews', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_reviews_patient_id'), 'reviews', ['patient_id'], unique=False)
    op.create_index(op.f('ix_reviews_service_id'), 'reviews', ['service_id'], unique=False)
    op.create_index('ix_reviews_unique_patient_doctor', 'reviews', ['patient_id', 'doctor_id'], unique=True, postgresql_where=sa.text('doctor_id IS NOT NULL'))
    op.create_index('ix_reviews_unique_patient_service', 'reviews', ['patient_id', 'service_id'], unique=True, postgresql_where=sa.text('service_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_unique_patient_service', table_name='reviews', postgresql_where=sa.text('service_id IS NOT NULL'))
    op.drop_index('ix_reviews_unique_patient_doctor', table_name='reviews', postgresql_where=sa.text('doctor_id IS NOT NULL'))
    op.drop_index(op.f('ix_reviews_service_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_patient_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_doctor_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
