"""create reviews table

Revision ID: 9bb06bd7b1f7
Revises: 75369e02cefc
Create Date: 2026-06-18 18:44:10.399433
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '9bb06bd7b1f7'
down_revision = '75369e02cefc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
