"""create services table

Revision ID: f8eeba0a8a7f
Revises: bb11701c12d6
Create Date: 2026-06-18 17:24:49.935416
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'f8eeba0a8a7f'
down_revision = 'bb11701c12d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
